package org.automatease.calendiary.data.local

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

/** Room database for the Calendiary app. */
@Database(entities = [DiaryEntryEntity::class], version = 1, exportSchema = true)
@ConstructedBy(DiaryDatabaseConstructor::class)
abstract class DiaryDatabase : RoomDatabase() {
    abstract fun diaryEntryDao(): DiaryEntryDao
}

/** KMP database constructor - actual implementation is generated by Room. */
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object DiaryDatabaseConstructor : RoomDatabaseConstructor<DiaryDatabase> {
    override fun initialize(): DiaryDatabase
}
